version: '3'

services:
    nginx:
        image: nginx:latest
        volumes:
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./wordpress:/var/www/html
        ports:
          - '80:80'
        depends_on: 
            - wp-headless
            - frontend-graphql
    db-headless:
        image: mariadb
        container_name: db-headless
        environment:
            - MYSQL_RANDOM_ROOT_PASSWORD=yes
            - MYSQL_DATABASE=${WORDPRESS_DB_NAME}
            - MYSQL_PASSWORD=${WORDPRESS_DB_PASSWORD}
            - MYSQL_USER=${WORDPRESS_DB_USER}
        ports:
            - '3307:3306'
    wp-headless:
        build: .
        container_name: wp-headless
        depends_on:
            - db-headless
        env_file: .env
        user: www-data
        volumes:
            - ./wordpress:/var/www/html
            - ./docker/install_wordpress.sh:/usr/local/bin/install_wordpress
            - ./docker/migratedb_import.sh:/usr/local/bin/migratedb_import
            - ./docker/postlightheadlesswpstarter.wordpress.xml:/var/www/postlightheadlesswpstarter.wordpress.xml
            - ./docker/images:/var/www/images
            - ./docker/plugins:/var/www/plugins
            - ./nginx/www.conf:/etc/php7.4/fpm/pool.d/www.conf
    frontend-graphql:
        command: bash -c 'yarn && yarn build && yarn start'
        container_name: frontend-graphql
        expose:
            - '3000'
        image: node:13
        ports:
            - '3000:3000'
        user: node
        volumes:
            - ./frontend:/home/node/app
        working_dir: /home/node/app
