version: '3'

services:
    nginx:
        image: nginx:latest
        command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
        volumes:
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./wordpress:/var/www/html
            - ./docker/certbot/conf:/etc/letsencrypt
            - ./docker/certbot/www:/var/www/certbot
        working_dir: /var/www/html
        ports:
          - '80:80'
          - "443:443"
        depends_on: 
            - wp-headless
            - frontend-graphql    
    certbot:
        image: certbot/certbot
        entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
        volumes:
            - ./docker/certbot/conf:/etc/letsencrypt
            - ./docker/certbot/www:/var/www/certbot
    db-headless:
        image: mariadb
        container_name: db-headless
        restart: always
        env_file: ./.env
        restart: on-failure
        environment:
            - MYSQL_RANDOM_ROOT_PASSWORD=yes
            - MYSQL_DATABASE=${WORDPRESS_DB_NAME}
            - MYSQL_PASSWORD=${WORDPRESS_DB_PASSWORD}
            - MYSQL_USER=${WORDPRESS_DB_USER}
        ports:
            - '3306:3306'
        expose: 
            - '3306'
        volumes:
            - maria-dbdata:/var/lib/mysql
    wp-headless:
        build: .
        container_name: wp-headless
        depends_on:
            - db-headless
        user: www-data
        ports:
            - '9000:9000'
        expose: 
            - '9000'
        volumes:
            - ./wordpress:/var/www/html
            - ./docker/install_wordpress.sh:/usr/local/bin/install_wordpress
            - ./docker/migratedb_import.sh:/usr/local/bin/migratedb_import
            - ./docker/postlightheadlesswpstarter.wordpress.xml:/var/www/postlightheadlesswpstarter.wordpress.xml
            - ./docker/images:/var/www/images
            - ./docker/plugins:/var/www/plugins
            - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    wp-setup: 
        build: ./docker/toolbox/
        volumes:
            - ./wordpress:/var/www/html
            - ./docker/plugins:/var/www/plugins
        working_dir: /var/www/html
        depends_on:
            - db-headless
        env_file: ./.env
        links:
            - db-headless
    frontend-graphql:
        command: bash -c 'yarn && yarn build && yarn start'
        container_name: frontend-graphql
        expose:
            - '3000'
        image: node:13
        ports:
            - '3000:3000'
        user: node
        volumes:
            - ./frontend:/home/node/app
        working_dir: /home/node/app


volumes:
    maria-dbdata:
